# Generated by Django 6.0 on 2026-01-19 08:56

import core.models
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_player_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playing',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'created_at': '2026-01-19T08:56:03.781238Z', 'layers': [], 'meta': {}}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=core.models.Cosound),
        ),
    ]
