# Generated by Django 6.0 on 2026-01-19 09:17

import core.models
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_alter_player_playing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="playing",
            field=django_pydantic_field.fields.PydanticSchemaField(
                config=None,
                default={
                    "created_at": "2026-01-19T09:17:55.830815Z",
                    "layers": [],
                    "meta": {},
                },
                schema=core.models.Cosound,
            ),
        ),
    ]
