# Generated by Django 6.0 on 2026-01-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='nvector',
            new_name='nvec',
        ),
    ]
