# Generated by Django 6.0 on 2026-01-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Player')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('cosound', models.JSONField(blank=True, default=dict, null=True, verbose_name='Cosound')),
            ],
        ),
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='sounds/audio/', verbose_name='Audio File')),
                ('title', models.CharField(max_length=255, verbose_name='Sound Title')),
                ('artist', models.CharField(max_length=255, verbose_name='Recording Artist')),
                ('type', models.CharField(choices=[('Instrumental', 'Instrumental'), ('Soundscape', 'Soundscape'), ('Vocal', 'Vocal Music')], max_length=50, verbose_name='Type of Sound')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Time Stamp')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(verbose_name='Upvote')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group')),
                ('cosound', models.JSONField(blank=True, default=dict, null=True, verbose_name='Cosound')),
            ],
        ),
    ]
