# Generated by Django 6.0 on 2026-01-19 07:23

import core.models
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sounds/')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Soundscape', 'Soundscape'), ('Instrumental', 'Instrumental')])),
                ('features', pgvector.django.vector.VectorField(dimensions=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing', django_pydantic_field.fields.PydanticSchemaField(config=None, default={'created_at': '2026-01-19T07:23:27.519875Z', 'layers': [], 'meta': {}}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=core.models.Cosound)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playeraccount')),
                ('library', models.ManyToManyField(blank=True, to='core.sound')),
            ],
        ),
    ]
