# Generated by Django 6.0 on 2026-01-19 09:04

import core.models
import django.core.serializers.json
import django_pydantic_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_player_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playing',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default={'created_at': '2026-01-19T09:04:20.750139Z', 'layers': [], 'meta': {}}, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=core.models.Cosound),
        ),
    ]
