# Generated by Django 6.0 on 2026-01-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Client Owner'),
        ),
        migrations.AddField(
            model_name='cosound',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player', verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='sound',
            name='nvec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.naturalvector', verbose_name='Natural Vector of Sound'),
        ),
        migrations.AddField(
            model_name='player',
            name='library',
            field=models.ManyToManyField(blank=True, to='app.sound', verbose_name='Library'),
        ),
        migrations.AddField(
            model_name='cosound',
            name='sounds',
            field=models.ManyToManyField(to='app.sound', verbose_name='Sounds'),
        ),
        migrations.AddField(
            model_name='vote',
            name='cosound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cosound', verbose_name='Cosound'),
        ),
        migrations.AddField(
            model_name='vote',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.player', verbose_name='Player'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Voter'),
        ),
    ]
