# Generated by Django 6.0 on 2026-01-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='cosound',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cosound'),
        ),
        migrations.AddField(
            model_name='player',
            name='cosound',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Cosound'),
        ),
        migrations.DeleteModel(
            name='Cosound',
        ),
    ]
